# Generated by Django 5.0.2 on 2024-02-25 11:57

import apps.base.models
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', apps.base.models.LowerCaseCharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': '4. Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', apps.base.models.LowerCaseCharField(max_length=50, primary_key=True, serialize=False, verbose_name='name')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name_plural': '1. Continents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', apps.base.models.LowerCaseCharField(max_length=100, primary_key=True, serialize=False, verbose_name='name')),
                ('iso_alpha2', apps.base.models.UpperCaseCharField(max_length=2, unique=True, verbose_name='iso_alpha2')),
                ('iso_alpha3', apps.base.models.UpperCaseCharField(max_length=3, unique=True, verbose_name='iso_alpha3')),
                ('iso_3116_2', apps.base.models.UpperCaseCharField(max_length=20, unique=True, verbose_name='iso_3116_2')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name_plural': '3. Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='address.city')),
            ],
            options={
                'verbose_name_plural': '5. Addresses',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.country'),
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', apps.base.models.LowerCaseCharField(max_length=50, verbose_name='name')),
                ('code', models.PositiveSmallIntegerField(verbose_name='code')),
                ('intermediate_region', apps.base.models.LowerCaseCharField(blank=True, max_length=50, verbose_name='intermediate region')),
                ('intermediate_region_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='intermediate region code')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.continent')),
            ],
            options={
                'verbose_name_plural': '2. Continents - Regions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.subregion'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('country'), name='city_country__unique'),
        ),
        migrations.AddConstraint(
            model_name='subregion',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('intermediate_region'), name='sub_region_name_intermediate_region_name__unique'),
        ),
        migrations.AddConstraint(
            model_name='subregion',
            constraint=models.UniqueConstraint(models.F('code'), models.F('intermediate_region_code'), name='sub_region_code_intermediate_region_code__unique'),
        ),
    ]
