# Generated by Django 5.0.2 on 2024-02-25 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_populate_city'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=125, verbose_name='Phone')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('job', models.CharField(blank=True, max_length=255, verbose_name='Job')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='address.address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
